#spring.application.name=server
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaSecuritvDemo
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect